name: MISTAKE619-PRIVATE-SERVER
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Xray
        run: |
          bash <(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)
          UUID=$(uuidgen)
          echo "UUID=$UUID" >> $GITHUB_ENV
          cat <<EOF > config.json
          {
            "inbounds": [{
              "port": 8080, "protocol": "vless",
              "settings": { "clients": [{"id": "$UUID"}], "decryption": "none" },
              "streamSettings": { "network": "ws", "wsSettings": { "path": "/mistake619" } }
            }],
            "outbounds": [{ "protocol": "freedom" }]
          }
          EOF
          sudo mv config.json /usr/local/etc/xray/config.json
          sudo systemctl start xray

      - name: Cloudflare Tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:8080 > tunnel.log 2>&1 &
          sleep 25
          TUNNEL_URL=$(grep -o 'https://.*\.trycloudflare.com' tunnel.log | head -n 1 | sed 's/https:\/\///')
          CONF="vless://${{ env.UUID }}@$TUNNEL_URL:443?encryption=none&security=tls&sni=$TUNNEL_URL&type=ws&host=$TUNNEL_URL&path=%2Fmistake619#MISTAKE619_DEEP"
          echo "FINAL_CONF=$(echo -n $CONF | base64)" >> $GITHUB_ENV

      - name: Push Config
        run: |
          echo "${{ env.FINAL_CONF }}" > latest_config.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add latest_config.txt
          git commit -m "Update Config" || echo "No changes"
          git push origin main --force
          
